import { Activity, AlertTriangle, CheckCircle2, CircleDot, FolderKanban, HeartPulse, Lightbulb, ListChecks, ShieldAlert } from 'lucide-react'

import type { PlannerToday } from '@/lib/momentum/planner/planner-service'
import type { MomentumDailyBrief } from '@/lib/momentum/ai/capabilities/morning-brief'

const METRIC_ITEMS = [
  { key: 'open_tasks', label: 'Open', icon: CircleDot },
  { key: 'due_today', label: 'Due today', icon: Activity },
  { key: 'overdue', label: 'Overdue', icon: AlertTriangle },
  { key: 'completed', label: 'Done', icon: CheckCircle2 },
] as const

function isMomentumBrief(brief: PlannerToday['brief'] | MomentumDailyBrief): brief is MomentumDailyBrief {
  return 'recommendation' in brief
}

function LegacyBriefHero({ brief }: { brief: PlannerToday['brief'] }) {
  return (
    <section className="rounded-2xl border border-[#eadfce] bg-[#2d241c] p-6 text-white shadow-[0_24px_70px_rgba(83,67,48,0.18)]">
      <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
        <div className="max-w-2xl">
          <div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.18em] text-[#f3debf]">
            <FolderKanban className="h-3.5 w-3.5" />
            Momentum Brief
          </div>
          <h1 className="mt-5 text-3xl font-light tracking-tight sm:text-5xl" style={{ fontFamily: 'Newsreader, Georgia, serif' }}>
            {brief.headline}
          </h1>
          <p className="mt-4 max-w-xl text-base leading-7 text-[#f3e7d7]">{brief.narrative}</p>
        </div>

        <div className="grid min-w-0 grid-cols-2 gap-3 sm:grid-cols-4 lg:min-w-[460px]">
          {METRIC_ITEMS.map(({ key, label, icon: Icon }) => (
            <div key={key} className="rounded-xl border border-white/10 bg-white/8 p-3">
              <div className="flex items-center gap-2 text-[#f3debf]">
                <Icon className="h-4 w-4" />
                <span className="text-[10px] font-bold uppercase tracking-[0.16em]">{label}</span>
              </div>
              <p className="mt-3 text-2xl font-semibold">{brief.metrics[key]}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

export function BriefHero({ brief }: { brief: PlannerToday['brief'] | MomentumDailyBrief }) {
  if (!isMomentumBrief(brief)) {
    return <LegacyBriefHero brief={brief} />
  }

  return (
    <section className="rounded-2xl border border-[#eadfce] bg-[#2d241c] p-6 text-white shadow-[0_24px_70px_rgba(83,67,48,0.18)]">
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">
        <div className="min-w-0">
          <div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.18em] text-[#f3debf]">
            <FolderKanban className="h-3.5 w-3.5" />
            Momentum Brief
          </div>
          <h1 className="mt-5 text-3xl font-light tracking-tight sm:text-5xl" style={{ fontFamily: 'Newsreader, Georgia, serif' }}>
            {brief.welcome}
          </h1>
          <p className="mt-4 max-w-2xl text-base leading-7 text-[#f3e7d7]">{brief.recommendation.summary}</p>

          <div className="mt-6 grid gap-3 sm:grid-cols-2">
            <div className="rounded-xl border border-white/10 bg-white/8 p-4">
              <div className="flex items-center gap-2 text-[#f3debf]">
                <Activity className="h-4 w-4" />
                <span className="text-[10px] font-bold uppercase tracking-[0.16em]">Execution Score</span>
              </div>
              <p className="mt-3 text-3xl font-semibold">{brief.execution_score.score} / 100</p>
              <p className="mt-2 text-xs leading-5 text-[#e8d7c0]">{brief.execution_score.explanation}</p>
            </div>
            <div className="rounded-xl border border-white/10 bg-white/8 p-4">
              <div className="flex items-center gap-2 text-[#f3debf]">
                <HeartPulse className="h-4 w-4" />
                <span className="text-[10px] font-bold uppercase tracking-[0.16em]">Workspace Health</span>
              </div>
              <p className="mt-3 text-2xl font-semibold">{brief.workspace_health.label}</p>
              <p className="mt-2 text-xs leading-5 text-[#e8d7c0]">{brief.workspace_health.reasons[0]}</p>
            </div>
          </div>
        </div>

        <aside className="rounded-xl border border-white/10 bg-white/8 p-4">
          <div className="flex items-center gap-2 text-[#f3debf]">
            <Lightbulb className="h-4 w-4" />
            <span className="text-[10px] font-bold uppercase tracking-[0.16em]">{brief.recommendation.title}</span>
          </div>
          <p className="mt-3 text-sm leading-6 text-[#f3e7d7]">{brief.recommendation.reasoning}</p>
          {brief.ai_run_id && <p className="mt-3 text-[11px] font-semibold text-[#cdbda6]">Generated by Momentum</p>}
          {brief.mode === 'fallback' && <p className="mt-3 text-[11px] font-semibold text-[#cdbda6]">Deterministic Momentum fallback</p>}
        </aside>
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-3">
        <div className="rounded-xl border border-white/10 bg-white/8 p-4">
          <div className="flex items-center gap-2 text-[#f3debf]">
            <ListChecks className="h-4 w-4" />
            <span className="text-[10px] font-bold uppercase tracking-[0.16em]">Today&apos;s Focus</span>
          </div>
          <div className="mt-4 space-y-3">
            {brief.top_priorities.length === 0 ? (
              <p className="text-sm text-[#e8d7c0]">Add due dates or start a task to create focus.</p>
            ) : (
              brief.top_priorities.map((task, index) => (
                <div key={task.id} className="text-sm leading-5 text-[#f3e7d7]">
                  <span className="font-semibold text-white">{index + 1}. {task.title}</span>
                  <p className="text-xs text-[#cdbda6]">{task.reason}</p>
                </div>
              ))
            )}
          </div>
        </div>

        <div className="rounded-xl border border-white/10 bg-white/8 p-4">
          <div className="flex items-center gap-2 text-[#f3debf]">
            <ShieldAlert className="h-4 w-4" />
            <span className="text-[10px] font-bold uppercase tracking-[0.16em]">Risks</span>
          </div>
          <div className="mt-4 space-y-3">
            {brief.at_risk_tasks.length === 0 ? (
              <p className="text-sm text-[#e8d7c0]">No high-risk task is active right now.</p>
            ) : (
              brief.at_risk_tasks.map((risk) => (
                <div key={risk.task_id} className="text-sm leading-5 text-[#f3e7d7]">
                  <span className="font-semibold text-white">{risk.task_title}</span>
                  <p className="text-xs text-[#cdbda6]">{risk.reason}</p>
                </div>
              ))
            )}
          </div>
        </div>

        <div className="rounded-xl border border-white/10 bg-white/8 p-4">
          <div className="flex items-center gap-2 text-[#f3debf]">
            <AlertTriangle className="h-4 w-4" />
            <span className="text-[10px] font-bold uppercase tracking-[0.16em]">Blockers</span>
          </div>
          <div className="mt-4 space-y-3">
            {brief.blockers.length === 0 ? (
              <p className="text-sm text-[#e8d7c0]">No blockers are currently marked.</p>
            ) : (
              brief.blockers.map((task) => (
                <div key={task.id} className="text-sm leading-5 text-[#f3e7d7]">
                  <span className="font-semibold text-white">{task.title}</span>
                  <p className="text-xs text-[#cdbda6]">{task.reason}</p>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      <div className="mt-4 grid min-w-0 grid-cols-2 gap-3 sm:grid-cols-4">
        {METRIC_ITEMS.map(({ key, label, icon: Icon }) => (
          <div key={key} className="rounded-xl border border-white/10 bg-white/8 p-3">
            <div className="flex items-center gap-2 text-[#f3debf]">
              <Icon className="h-4 w-4" />
              <span className="text-[10px] font-bold uppercase tracking-[0.16em]">{label}</span>
            </div>
            <p className="mt-3 text-2xl font-semibold">{brief.metrics[key]}</p>
          </div>
        ))}
      </div>
    </section>
  )
}
